Dato1=int (input("Ingrese el dato 1 : "))
Dato2=int (input("Ingrese el dato 2 : "))
sum= (Dato1 + Dato2)
resta= (Dato1 - Dato2)
div= (Dato1 / Dato2)
mul= (Dato1 * Dato2)
print("La suma es igual a: ",sum)
print("La resta es igual a: ", resta)
print("La divicion es igual a: ",div)
print("La multiplicacion es igual a: ",mul)